export const CONSTITUENCIES = {
  'AN': [{ code: 'AN1', value: 'Andaman and Nicobar Islands', ministers: [{name: 'Bishnu Pada Ray', id: 'm-an1'}]}],
  'AP':[
    { code: 'AP1', value: 'Amalapuram', ministers: [{name: 'Pandula Ravindra Babu', id: 'm-ap1'}]} ,
    { code: 'AP2', value: 'Anakapalli', ministers: [{name: 'Muttamsetti Srinivasa Rao (Avanthi)', id: 'm-ap2'}]} ,
    { code: 'AP3', value: 'Anantapur', ministers: [{name: 'J.C. Divakar Reddi', id: 'm-ap3'}]} ,
    { code: 'AP4', value: 'Araku', ministers: [{name: 'Kothapalli Geetha', id: 'm-ap4'}]} ,
    { code: 'AP5', value: 'Bapatla', ministers: [{name: 'Malyadri Sriram', id: 'm-ap5'}]} ,
    { code: 'AP6', value: 'Chittoor', ministers: [{name: 'Naramalli Sivaprasad', id: 'm-ap6'}]} ,
    { code: 'AP7', value: 'Eluru', ministers: [{name: 'Maganti Venkateswara Rao (Babu)', id: 'm-ap7'}]} ,
    { code: 'AP8', value: 'Guntur', ministers: [{name: 'Jayadev Galla', id: 'm-ap8'}]} ,
    { code: 'AP9', value: 'Hindupur', ministers: [{name: 'Kristappa Nimmala', id: 'm-ap9'}]} ,
    { code: 'AP10', value: 'Kadapa', ministers: [{name: 'Y.S. Avinash Reddy', id: 'm-ap10'}]} ,
    { code: 'AP11', value: 'Kakinada', ministers: [{name: 'Thota Narasimham', id: 'm-ap11'}]} ,
    { code: 'AP12', value: 'Kurnool', ministers: [{name: 'Butta Renuka', id: 'm-ap12'}]} ,
    { code: 'AP13', value: 'Machilipatnam', ministers: [{name: 'Konakalla Narayana Rao', id: 'm-ap13'}]} ,
    { code: 'AP14', value: 'Nandyal', ministers: [{name: 'S.P.Y. Reddy', id: 'm-ap14'}]} ,
    { code: 'AP15', value: 'Narasaraopet', ministers: [{name: 'Sambasiva Rayapati Rao', id: 'm-ap15'}]} ,
    { code: 'AP16', value: 'Narsapuram', ministers: [{name: 'Gokaraju Ganga Raju', id: 'm-ap16'}]} ,
    { code: 'AP17', value: 'Nellore', ministers: [{name: 'Mekapati Rajamohan Reddy', id: 'm-ap17'}]} ,
    { code: 'AP18', value: 'Ongole', ministers: [{name: 'Y.V. Subba Reddy', id: 'm-ap18'}]} ,
    { code: 'AP19', value: 'Rajahmundry', ministers: [{name: 'Murali Mohan Maganti', id: 'm-ap19'}]} ,
    { code: 'AP20', value: 'Rajampet', ministers: [{name: 'P.V. Midhun Reddy', id: 'm-ap20'}]} ,
    { code: 'AP21', value: 'Srikakulam', ministers: [{name: 'Rammohan Naidu Kinjarapu', id: 'm-ap21'}]} ,
    { code: 'AP22', value: 'Tirupati', ministers: [{name: 'Varaprasad Rao Velagapalli', id: 'm-ap22'}]} ,
    { code: 'AP23', value: 'Vijayawada', ministers: [{name: 'Kesineni Srinivas', id: 'm-ap23'}]} ,
    { code: 'AP24', value: 'Visakhapatnam', ministers: [{name: 'Kambhampati Hari Babu', id: 'm-ap24'}]} ,
    { code: 'AP25', value: 'Vizianagaram', ministers: [{name: 'Ashok Gajapathi Raju Pusapati', id: 'm-ap25'}]}
  ],

  'AR':[{ code: 'AR1', value: 'Arunachal West', ministers: [{name: 'Kiren Rijiju', id: 'm-ar1'}]} ,
    { code: 'AR2', value: 'Arunachal East', ministers: [{name: 'Ninong Ering', id: 'm-ar2'}]} ],

  'AS':[{ code: 'AS1', value: 'Autonomous District', ministers: [{name: 'Biren Singh Engti', id: 'm-as1'}]} ,
    { code: 'AS2', value: 'Barpeta', ministers: [{name: 'Siraj Uddin Ajmal', id: 'm-as2'}]} ,
    { code: 'AS3', value: 'Dhubri', ministers: [{name: 'Badruddin Ajmal', id: 'm-as3'}]} ,
    { code: 'AS4', value: 'Dibrugarh', ministers: [{name: 'Rameswar Teli', id: 'm-as4'}]} ,
    { code: 'AS5', value: 'Gauhati', ministers: [{name: 'Bijoya Chakravarty', id: 'm-as5'}]} ,
    { code: 'AS6', value: 'Jorhat', ministers: [{name: 'Kamakhya Prasad Tasa', id: 'm-as6'}]} ,
    { code: 'AS7', value: 'Kaliabor', ministers: [{name: 'Gourav Gogoi', id: 'm-as7'}]} ,
    { code: 'AS8', value: 'Karimganj', ministers: [{name: 'Radheshyam Biswas', id: 'm-as8'}]} ,
    { code: 'AS9', value: 'Kokrajhar', ministers: [{name: 'Naba Kumar Sarania (Hira)', id: 'm-as9'}]} ,
    { code: 'AS10', value: 'Lakhimpur', ministers: [{name: 'Pradan Baruah', id: 'm-as10'}]} ,
    { code: 'AS11', value: 'Lakhimpur', ministers: [{name: 'Sarbananda Sonowal', id: 'm-as11'}]} ,
    { code: 'AS12', value: 'Mangaldoi', ministers: [{name: 'Ramen Deka', id: 'm-as12'}]} ,
    { code: 'AS13', value: 'Nawgong', ministers: [{name: 'Rajen Gohain', id: 'm-as13'}]} ,
    { code: 'AS14', value: 'Silchar', ministers: [{name: 'Sushmita Dev', id: 'm-as14'}]} ,
    { code: 'AS15', value: 'Tezpur', ministers: [{name: 'Ram Prasad Sarmah', id: 'm-as15'}]} ]

};
