export interface Constituency {
  code: string;
  value: string;
  ministers: Array<MinisterCopy>;
}

export interface MinisterCopy {
  name: string;
  id: string;
}

export const CONSTITUENCIES ={'AN': [{ code: 'AN1', value: 'Andaman and Nicobar Islands', ministers: [{name: 'Bishnu Pada Ray', id: 'm-an1'}]}],

  'AP':[
    { code: 'AP1', value: 'Amalapuram', ministers: [{name: 'Pandula Ravindra Babu', id: 'm-ap1'}]} ,
    { code: 'AP2', value: 'Anakapalli', ministers: [{name: 'Muttamsetti Srinivasa Rao (Avanthi)', id: 'm-ap2'}]} ,
    { code: 'AP3', value: 'Anantapur', ministers: [{name: 'J.C. Divakar Reddi', id: 'm-ap3'}]} ,
    { code: 'AP4', value: 'Araku', ministers: [{name: 'Kothapalli Geetha', id: 'm-ap4'}]} ,
    { code: 'AP5', value: 'Bapatla', ministers: [{name: 'Malyadri Sriram', id: 'm-ap5'}]} ,
    { code: 'AP6', value: 'Chittoor', ministers: [{name: 'Naramalli Sivaprasad', id: 'm-ap6'}]} ,
    { code: 'AP7', value: 'Eluru', ministers: [{name: 'Maganti Venkateswara Rao (Babu)', id: 'm-ap7'}]} ,
    { code: 'AP8', value: 'Guntur', ministers: [{name: 'Jayadev Galla', id: 'm-ap8'}]} ,
    { code: 'AP9', value: 'Hindupur', ministers: [{name: 'Kristappa Nimmala', id: 'm-ap9'}]} ,
    { code: 'AP10', value: 'Kadapa', ministers: [{name: 'Y.S. Avinash Reddy', id: 'm-ap10'}]} ,
    { code: 'AP11', value: 'Kakinada', ministers: [{name: 'Thota Narasimham', id: 'm-ap11'}]} ,
    { code: 'AP12', value: 'Kurnool', ministers: [{name: 'Butta Renuka', id: 'm-ap12'}]} ,
    { code: 'AP13', value: 'Machilipatnam', ministers: [{name: 'Konakalla Narayana Rao', id: 'm-ap13'}]} ,
    { code: 'AP14', value: 'Nandyal', ministers: [{name: 'S.P.Y. Reddy', id: 'm-ap14'}]} ,
    { code: 'AP15', value: 'Narasaraopet', ministers: [{name: 'Sambasiva Rayapati Rao', id: 'm-ap15'}]} ,
    { code: 'AP16', value: 'Narsapuram', ministers: [{name: 'Gokaraju Ganga Raju', id: 'm-ap16'}]} ,
    { code: 'AP17', value: 'Nellore', ministers: [{name: 'Mekapati Rajamohan Reddy', id: 'm-ap17'}]} ,
    { code: 'AP18', value: 'Ongole', ministers: [{name: 'Y.V. Subba Reddy', id: 'm-ap18'}]} ,
    { code: 'AP19', value: 'Rajahmundry', ministers: [{name: 'Murali Mohan Maganti', id: 'm-ap19'}]} ,
    { code: 'AP20', value: 'Rajampet', ministers: [{name: 'P.V. Midhun Reddy', id: 'm-ap20'}]} ,
    { code: 'AP21', value: 'Srikakulam', ministers: [{name: 'Rammohan Naidu Kinjarapu', id: 'm-ap21'}]} ,
    { code: 'AP22', value: 'Tirupati', ministers: [{name: 'Varaprasad Rao Velagapalli', id: 'm-ap22'}]} ,
    { code: 'AP23', value: 'Vijayawada', ministers: [{name: 'Kesineni Srinivas', id: 'm-ap23'}]} ,
    { code: 'AP24', value: 'Visakhapatnam', ministers: [{name: 'Kambhampati Hari Babu', id: 'm-ap24'}]} ,
    { code: 'AP25', value: 'Vizianagaram', ministers: [{name: 'Ashok Gajapathi Raju Pusapati', id: 'm-ap25'}]} ],

  'AR':[
    { code: 'AR1', value: 'Arunachal West', ministers: [{name: 'Kiren Rijiju', id: 'm-ar1'}]} ,
    { code: 'AR2', value: 'Arunachal East', ministers: [{name: 'Ninong Ering', id: 'm-ar2'}]} ],

  'AS':[
    { code: 'AS1', value: 'Autonomous District', ministers: [{name: 'Biren Singh Engti', id: 'm-as1'}]} ,
    { code: 'AS2', value: 'Barpeta', ministers: [{name: 'Siraj Uddin Ajmal', id: 'm-as2'}]} ,
    { code: 'AS3', value: 'Dhubri', ministers: [{name: 'Badruddin Ajmal', id: 'm-as3'}]} ,
    { code: 'AS4', value: 'Dibrugarh', ministers: [{name: 'Rameswar Teli', id: 'm-as4'}]} ,
    { code: 'AS5', value: 'Gauhati', ministers: [{name: 'Bijoya Chakravarty', id: 'm-as5'}]} ,
    { code: 'AS6', value: 'Jorhat', ministers: [{name: 'Kamakhya Prasad Tasa', id: 'm-as6'}]} ,
    { code: 'AS7', value: 'Kaliabor', ministers: [{name: 'Gourav Gogoi', id: 'm-as7'}]} ,
    { code: 'AS8', value: 'Karimganj', ministers: [{name: 'Radheshyam Biswas', id: 'm-as8'}]} ,
    { code: 'AS9', value: 'Kokrajhar', ministers: [{name: 'Naba Kumar Sarania (Hira)', id: 'm-as9'}]} ,
    { code: 'AS11', value: 'Lakhimpur', ministers: [{name: 'Sarbananda Sonowal', id: 'm-as11'}]} ,
    { code: 'AS12', value: 'Mangaldoi', ministers: [{name: 'Ramen Deka', id: 'm-as12'}]} ,
    { code: 'AS13', value: 'Nawgong', ministers: [{name: 'Rajen Gohain', id: 'm-as13'}]} ,
    { code: 'AS14', value: 'Silchar', ministers: [{name: 'Sushmita Dev', id: 'm-as14'}]} ,
    { code: 'AS15', value: 'Tezpur', ministers: [{name: 'Ram Prasad Sarmah', id: 'm-as15'}]} ],

  'BR':[
    { code: 'BR1', value: 'Araria', ministers: [{name: 'Sarfaraz Alam', id: 'm-br1'}]} ,
    { code: 'BR3', value: 'Arrah', ministers: [{name: 'Raj Kumar Singh', id: 'm-br3'}]} ,
    { code: 'BR4', value: 'Aurangabad', ministers: [{name: 'Sushil Kumar Singh', id: 'm-br4'}]} ,
    { code: 'BR5', value: 'Banka', ministers: [{name: 'Jai Prakash Narayan Yadav', id: 'm-br5'}]} ,
    { code: 'BR6', value: 'Begusarai', ministers: [{name: 'Dr Bhola Singh', id: 'm-br6'}]} ,
    { code: 'BR7', value: 'Bhagalpur', ministers: [{name: 'Shailesh Kumar Urph Bulo Mandal', id: 'm-br7'}]} ,
    { code: 'BR8', value: 'Buxar', ministers: [{name: 'Ashwini Kumar Choubey', id: 'm-br8'}]} ,
    { code: 'BR9', value: 'Darbhanga', ministers: [{name: 'Kirti (Jha) Azad', id: 'm-br9'}]} ,
    { code: 'BR10', value: 'Gaya', ministers: [{name: 'Hari Manjhi', id: 'm-br10'}]} ,
    { code: 'BR11', value: 'Gopalganj', ministers: [{name: 'Janak Ram', id: 'm-br11'}]} ,
    { code: 'BR12', value: 'Hajipur', ministers: [{name: 'Ram Vilas Paswan', id: 'm-br12'}]} ,
    { code: 'BR13', value: 'Jahanabad', ministers: [{name: 'Arun Kumar', id: 'm-br13'}]} ,
    { code: 'BR14', value: 'Jamui', ministers: [{name: 'Chirag Kumar Paswan', id: 'm-br14'}]} ,
    { code: 'BR15', value: 'Jhanjharpur', ministers: [{name: 'Birendra Kumar Chaudhary', id: 'm-br15'}]} ,
    { code: 'BR16', value: 'Karakat', ministers: [{name: 'Upendra Kushwaha', id: 'm-br16'}]} ,
    { code: 'BR17', value: 'Katihar', ministers: [{name: 'Tariq Anwar', id: 'm-br17'}]} ,
    { code: 'BR18', value: 'Khagaria', ministers: [{name: 'Mahboob Ali Kaiser', id: 'm-br18'}]} ,
    { code: 'BR19', value: 'Kishanganj', ministers: [{name: 'Asrarul Haque Mohammad', id: 'm-br19'}]} ,
    { code: 'BR20', value: 'Madhepura', ministers: [{name: 'Rajesh Ranjan @ Pappu Yadav', id: 'm-br20'}]} ,
    { code: 'BR21', value: 'Madhubani', ministers: [{name: 'Hukamdeo Narayan Yadav', id: 'm-br21'}]} ,
    { code: 'BR22', value: 'Maharajganj', ministers: [{name: 'Janardan Singh Sigriwal', id: 'm-br22'}]} ,
    { code: 'BR23', value: 'Munger', ministers: [{name: 'Veena Devi', id: 'm-br23'}]} ,
    { code: 'BR24', value: 'Muzaffarpur', ministers: [{name: 'Ajay Nishad', id: 'm-br24'}]} ,
    { code: 'BR25', value: 'Nalanda', ministers: [{name: 'Kaushalendra Kumar', id: 'm-br25'}]} ,
    { code: 'BR26', value: 'Nawada', ministers: [{name: 'Giriraj Singh', id: 'm-br26'}]} ,
    { code: 'BR27', value: 'Paschim Champaran', ministers: [{name: 'Sanjay Jaiswal', id: 'm-br27'}]} ,
    { code: 'BR28', value: 'Pataliputra', ministers: [{name: 'Ram Kripal Yadav', id: 'm-br28'}]} ,
    { code: 'BR29', value: 'Patna Sahib', ministers: [{name: 'Shatrughan Sinha', id: 'm-br29'}]} ,
    { code: 'BR30', value: 'Purnia', ministers: [{name: 'Santosh Kumar', id: 'm-br30'}]} ,
    { code: 'BR31', value: 'Purvi Champaran', ministers: [{name: 'Radha Mohan Singh', id: 'm-br31'}]} ,
    { code: 'BR32', value: 'Samastipur', ministers: [{name: 'Ram Chandra Paswan', id: 'm-br32'}]} ,
    { code: 'BR33', value: 'Saran', ministers: [{name: 'Rajiv Pratap Rudy', id: 'm-br33'}]} ,
    { code: 'BR34', value: 'Sasaram', ministers: [{name: 'Chhedi Paswan', id: 'm-br34'}]} ,
    { code: 'BR35', value: 'Sheohar', ministers: [{name: 'Rama Devi', id: 'm-br35'}]} ,
    { code: 'BR36', value: 'Sitamarhi', ministers: [{name: 'Ram Kumar Sharma', id: 'm-br36'}]} ,
    { code: 'BR37', value: 'Siwan', ministers: [{name: 'Om Prakash Yadav', id: 'm-br37'}]} ,
    { code: 'BR38', value: 'Supaul', ministers: [{name: 'Ranjeet Ranjan', id: 'm-br38'}]} ,
    { code: 'BR39', value: 'Ujiarpur', ministers: [{name: 'Nityanand Rai', id: 'm-br39'}]} ,
    { code: 'BR40', value: 'Vaishali', ministers: [{name: 'Rama Kishore Singh', id: 'm-br40'}]} ,
    { code: 'BR41', value: 'Valmiki Nagar', ministers: [{name: 'Satish Chandra Dubey', id: 'm-br41'}]} ],


  'CG': [{ code: 'CG1', value: 'Chandigarh', ministers: [{name: 'Kirron Anupam Kher', id: 'm-cg1'}]} ],

  'CH':[
    { code: 'CH1', value: 'Bastar', ministers: [{name: 'Dinesh Kashyap', id: 'm-ch1'}]} ,
    { code: 'CH2', value: 'Bilaspur', ministers: [{name: 'Lakhan Lal Sahu', id: 'm-ch2'}]} ,
    { code: 'CH3', value: 'Durg', ministers: [{name: 'Tamradhwaj Sahu', id: 'm-ch3'}]} ,
    { code: 'CH4', value: 'Janjgir-Champa', ministers: [{name: 'Kamla Devi Patle', id: 'm-ch4'}]} ,
    { code: 'CH5', value: 'Kanker', ministers: [{name: 'Vikram Dev Usendi', id: 'm-ch5'}]} ,
    { code: 'CH6', value: 'Korba', ministers: [{name: 'Banshilal Mahto', id: 'm-ch6'}]} ,
    { code: 'CH7', value: 'Mahasamund', ministers: [{name: 'Chandu Lal Sahu', id: 'm-ch7'}]} ,
    { code: 'CH8', value: 'Raigarh', ministers: [{name: 'Vishnu Deo Sai', id: 'm-ch8'}]} ,
    { code: 'CH9', value: 'Raipur', ministers: [{name: 'Ramesh Bais', id: 'm-ch9'}]} ,
    { code: 'CH10', value: 'Rajnandgaon', ministers: [{name: 'Abhishek Singh', id: 'm-ch10'}]} ,
    { code: 'CH11', value: 'Surguja', ministers: [{name: 'Kamalbhan Singh Marabi', id: 'm-ch11'}]} ],


  'DH':[{ code: 'DH1', value: 'Dadra and Nagar Haveli', ministers: [{name: 'Natubhai Gomanbhai Patel', id: 'm-dh1'}]} ],


  'DD':[{ code: 'DD1', value: 'Daman and Diu', ministers: [{name: 'Lalubhai Babubhai Patel', id: 'm-dd1'}]} ],

  'DL':[
    { code: 'DL1', value: 'Chandni Chowk', ministers: [{name: 'Harsh Vardhan', id: 'm-dl1'}]} ,
    { code: 'DL2', value: 'East Delhi', ministers: [{name: 'Maheish Girri', id: 'm-dl2'}]} ,
    { code: 'DL3', value: 'New Delhi', ministers: [{name: 'Meenakashi Lekhi', id: 'm-dl3'}]} ,
    { code: 'DL4', value: 'North East Delhi', ministers: [{name: 'Manoj Tiwari', id: 'm-dl4'}]} ,
    { code: 'DL5', value: 'North West Delhi', ministers: [{name: 'Udit Raj', id: 'm-dl5'}]} ,
    { code: 'DL6', value: 'South Delhi', ministers: [{name: 'Ramesh Bidhuri', id: 'm-dl6'}]} ,
    { code: 'DL7', value: 'West Delhi', ministers: [{name: 'Parvesh Sahib Singh Verma', id: 'm-dl7'}]} ],

  'GA':[
    { code: 'GA1', value: 'South Goa', ministers: [{name: 'Narendra Keshav Sawaikar', id: 'm-ga1'}]} ,
    { code: 'GA2', value: 'North Goa', ministers: [{name: 'Shripad Yesso Naik', id: 'm-ga2'}]} ],

  'GJ':[
    { code: 'GJ1', value: 'Ahmedabad East', ministers: [{name: 'Paresh Rawal', id: 'm-gj1'}]} ,
    { code: 'GJ2', value: 'Ahmedabad West', ministers: [{name: 'Kirit Premjibhai Solanki', id: 'm-gj2'}]} ,
    { code: 'GJ3', value: 'Amreli', ministers: [{name: 'Naranbhai Kachhadia', id: 'm-gj3'}]} ,
    { code: 'GJ4', value: 'Anand', ministers: [{name: 'Dilip Patel', id: 'm-gj4'}]} ,
    { code: 'GJ5', value: 'Banaskantha', ministers: [{name: 'Haribhai Parthibhai Chaudhary', id: 'm-gj5'}]} ,
    { code: 'GJ6', value: 'Bardoli', ministers: [{name: 'Vasava Parbhubhai Nagarbhai', id: 'm-gj6'}]} ,
    { code: 'GJ7', value: 'Bharuch', ministers: [{name: 'Mansukhbhai D. Vasava', id: 'm-gj7'}]} ,
    { code: 'GJ8', value: 'Bhavnagar', ministers: [{name: 'Bharatiben Dhirubhai Shiyal', id: 'm-gj8'}]} ,
    { code: 'GJ9', value: 'Chhota Udaipur', ministers: [{name: 'Ramsinhbhai Patalyabhai Rathwa', id: 'm-gj9'}]} ,
    { code: 'GJ10', value: 'Dahod', ministers: [{name: 'Jasvantsinh Sumanbhai Bhabhor', id: 'm-gj10'}]} ,
    { code: 'GJ11', value: 'Gandhinagar', ministers: [{name: 'Lal Krishna Advani', id: 'm-gj11'}]} ,
    { code: 'GJ12', value: 'Jamnagar', ministers: [{name: 'Poonamben Hematbhai Maadam', id: 'm-gj12'}]} ,
    { code: 'GJ13', value: 'Junagadh', ministers: [{name: 'Chudasama Rajeshbhai Naranbhai', id: 'm-gj13'}]} ,
    { code: 'GJ14', value: 'Kachchh', ministers: [{name: 'Chavda Vinod Lakhamashi', id: 'm-gj14'}]} ,
    { code: 'GJ15', value: 'Kheda', ministers: [{name: 'Chauhan Devusinh Jesingbhai', id: 'm-gj15'}]} ,
    { code: 'GJ16', value: 'Mehesana', ministers: [{name: 'Jayshreeben Kanubhai Patel', id: 'm-gj16'}]} ,
    { code: 'GJ17', value: 'Navsari', ministers: [{name: 'C. R. Patil', id: 'm-gj17'}]} ,
    { code: 'GJ18', value: 'Panchmahal', ministers: [{name: 'Prabhatsinh Pratapsinh Chauhan', id: 'm-gj18'}]} ,
    { code: 'GJ19', value: 'Patan', ministers: [{name: 'Liladharbhai Khodaji Vaghela', id: 'm-gj19'}]} ,
    { code: 'GJ20', value: 'Porbandar', ministers: [{name: 'Vitthalbhai Hansrajbhai Radadiya', id: 'm-gj20'}]} ,
    { code: 'GJ21', value: 'Rajkot', ministers: [{name: 'Mohanbhai Kalyanjibhai Kundariya', id: 'm-gj21'}]} ,
    { code: 'GJ22', value: 'Sabarkantha', ministers: [{name: 'Rathod Dipsinh Shankarsinh', id: 'm-gj22'}]} ,
    { code: 'GJ23', value: 'Surat', ministers: [{name: 'Darshana Vikram Jardosh', id: 'm-gj23'}]} ,
    { code: 'GJ24', value: 'Surendranagar', ministers: [{name: 'Fatepara Devajibhai Govindbhai', id: 'm-gj24'}]} ,
    { code: 'GJ25', value: 'Vadodara', ministers: [{name: 'Ranjanben Bhatt', id: 'm-gj25'}]} ,
    { code: 'GJ26', value: 'Valsad', ministers: [{name: 'K.C. Patel', id: 'm-gj26'}]} ],

  'HR':[
    { code: 'HR1', value: 'Ambala', ministers: [{name: 'Rattan Lal Kataria', id: 'm-hr1'}]} ,
    { code: 'HR2', value: 'Bhiwani-Mahendragarh', ministers: [{name: 'Dharambir', id: 'm-hr2'}]} ,
    { code: 'HR3', value: 'Faridabad', ministers: [{name: 'Krishan Pal', id: 'm-hr3'}]} ,
    { code: 'HR4', value: 'Gurgaon', ministers: [{name: 'Inderjit Singh Rao', id: 'm-hr4'}]} ,
    { code: 'HR5', value: 'Hisar', ministers: [{name: 'Dushyant Chautala', id: 'm-hr5'}]} ,
    { code: 'HR6', value: 'Karnal', ministers: [{name: 'Ashwini Kumar', id: 'm-hr6'}]} ,
    { code: 'HR7', value: 'Kurukshetra', ministers: [{name: 'Raj Kumar Saini', id: 'm-hr7'}]} ,
    { code: 'HR8', value: 'Rohtak', ministers: [{name: 'Deepender Singh Hooda', id: 'm-hr8'}]} ,
    { code: 'HR9', value: 'Sirsa', ministers: [{name: 'Charanjeet Singh Rori', id: 'm-hr9'}]} ,
    { code: 'HR10', value: 'Sonipat', ministers: [{name: 'Ramesh Chander Kaushik', id: 'm-hr10'}]} ],

  'HP':[
    { code: 'HP1', value: 'Hamirpur', ministers: [{name: 'Anurag Singh Thakur', id: 'm-hp1'}]} ,
    { code: 'HP2', value: 'Kangra', ministers: [{name: 'Shanta Kumar', id: 'm-hp2'}]} ,
    { code: 'HP3', value: 'Mandi', ministers: [{name: 'Ram Swaroop Sharma', id: 'm-hp3'}]} ,
    { code: 'HP4', value: 'Shimla', ministers: [{name: 'Virender Kashyap', id: 'm-hp4'}]} ],

  'JK':[
    { code: 'JK1', value: 'Anantnag', ministers: [{name: 'Mehbooba Mufti', id: 'm-jk1'}]} ,
    { code: 'JK2', value: 'Baramulla', ministers: [{name: 'Muzaffar Hussain Baig', id: 'm-jk2'}]} ,
    { code: 'JK3', value: 'Jammu', ministers: [{name: 'Jugal Kishore', id: 'm-jk3'}]} ,
    { code: 'JK4', value: 'Ladakh', ministers: [{name: 'Thupstan Chhewang', id: 'm-jk4'}]} ,
    { code: 'JK5', value: 'Srinagar', ministers: [{name: 'Farooq Abdullah', id: 'm-jk5'}]} ,
    { code: 'JK7', value: 'Udhampur', ministers: [{name: 'Jitendra Singh', id: 'm-jk7'}]} ],

  'JH':[
    { code: 'JH1', value: 'Chatra', ministers: [{name: 'Sunil Kumar Singh', id: 'm-jh1'}]} ,
    { code: 'JH2', value: 'Dhanbad', ministers: [{name: 'Pashupati Nath Singh', id: 'm-jh2'}]} ,
    { code: 'JH3', value: 'Dumka', ministers: [{name: 'Shibu Soren', id: 'm-jh3'}]} ,
    { code: 'JH4', value: 'Giridih', ministers: [{name: 'Ravindra Kumar Pandey', id: 'm-jh4'}]} ,
    { code: 'JH5', value: 'Godda', ministers: [{name: 'Nishikant Dubey', id: 'm-jh5'}]} ,
    { code: 'JH6', value: 'Hazaribagh', ministers: [{name: 'Jayant Sinha', id: 'm-jh6'}]} ,
    { code: 'JH7', value: 'Jamshedpur', ministers: [{name: 'Bidyut Baran Mahato', id: 'm-jh7'}]} ,
    { code: 'JH8', value: 'Khunti', ministers: [{name: 'Kariya Munda', id: 'm-jh8'}]} ,
    { code: 'JH9', value: 'Kodarma', ministers: [{name: 'Ravindra Kumar Ray', id: 'm-jh9'}]} ,
    { code: 'JH10', value: 'Lohardaga', ministers: [{name: 'Sudarshan Bhagat', id: 'm-jh10'}]} ,
    { code: 'JH11', value: 'Palamu', ministers: [{name: 'Vishnu Dayal Ram', id: 'm-jh11'}]} ,
    { code: 'JH12', value: 'Rajmahal', ministers: [{name: 'Vijay Kumar Hansdak', id: 'm-jh12'}]} ,
    { code: 'JH13', value: 'Ranchi', ministers: [{name: 'Ram Tahal Choudhary', id: 'm-jh13'}]} ,
    { code: 'JH14', value: 'Singhbhum', ministers: [{name: 'Laxman Giluwa', id: 'm-jh14'}]} ],

  'KA':[
    { code: 'KA1', value: 'Bagalkot', ministers: [{name: 'P.C. Gaddigoudar', id: 'm-ka1'}]} ,
    { code: 'KA2', value: 'Bangalore Central', ministers: [{name: 'P. C. Mohan', id: 'm-ka2'}]} ,
    { code: 'KA3', value: 'Bangalore North', ministers: [{name: 'D.V. Sadananda Gowda', id: 'm-ka3'}]} ,
    { code: 'KA4', value: 'Bangalore Rural', ministers: [{name: 'D.K. Suresh', id: 'm-ka4'}]} ,
    { code: 'KA5', value: 'Bangalore South', ministers: [{name: 'Ananth Kumar', id: 'm-ka5'}]} ,
    { code: 'KA6', value: 'Belgaum', ministers: [{name: 'Suresh Channabasappa Angadi', id: 'm-ka6'}]} ,
    { code: 'KA7', value: 'Bellary', ministers: [{name: 'B. Sreeramulu', id: 'm-ka7'}]} ,
    { code: 'KA8', value: 'Bidar', ministers: [{name: 'Bhagwanth Khuba', id: 'm-ka8'}]} ,
    { code: 'KA9', value: 'Bijapur', ministers: [{name: 'Ramesh Chandappa Jigajinagi', id: 'm-ka9'}]} ,
    { code: 'KA10', value: 'Chamrajanagar', ministers: [{name: 'Dhruva Narayana Rangaswamy', id: 'm-ka10'}]} ,
    { code: 'KA11', value: 'Chikkballapur', ministers: [{name: 'M. Veerappa Moily', id: 'm-ka11'}]} ,
    { code: 'KA12', value: 'Chikkodi', ministers: [{name: 'Prakash Babanna Hukkeri', id: 'm-ka12'}]} ,
    { code: 'KA13', value: 'Chitradurga', ministers: [{name: 'B.N. Chandrappa', id: 'm-ka13'}]} ,
    { code: 'KA14', value: 'Dakshina Kannada', ministers: [{name: 'Nalin Kumar Kateel', id: 'm-ka14'}]} ,
    { code: 'KA15', value: 'Davanagere', ministers: [{name: 'Gowdar Mallikarjunappa Siddeswara', id: 'm-ka15'}]} ,
    { code: 'KA16', value: 'Dharwad', ministers: [{name: 'Pralhad Venkatesh Joshi', id: 'm-ka16'}]} ,
    { code: 'KA17', value: 'Gulbarga', ministers: [{name: 'Mallikarjun Kharge', id: 'm-ka17'}]} ,
    { code: 'KA18', value: 'Hassan', ministers: [{name: 'H.D. Devegowda', id: 'm-ka18'}]} ,
    { code: 'KA19', value: 'Haveri', ministers: [{name: 'Udasi Shivkumar Chanabasappa', id: 'm-ka19'}]} ,
    { code: 'KA20', value: 'Kolar', ministers: [{name: 'K.H. Muniyappa', id: 'm-ka20'}]} ,
    { code: 'KA21', value: 'Koppal', ministers: [{name: 'Karadi Sanganna Amarappa', id: 'm-ka21'}]} ,
    { code: 'KA22', value: 'Mandya', ministers: [{name: 'C.S. Puttaraju', id: 'm-ka22'}]} ,
    { code: 'KA23', value: 'Mysore', ministers: [{name: 'Prathap Simha', id: 'm-ka23'}]} ,
    { code: 'KA24', value: 'Raichur', ministers: [{name: 'B.V. Nayak', id: 'm-ka24'}]} ,
    { code: 'KA25', value: 'Shimoga', ministers: [{name: 'B. S. Yeddyurappa', id: 'm-ka25'}]} ,
    { code: 'KA26', value: 'Tumkur', ministers: [{name: 'S.P. Muddahanumegowda', id: 'm-ka26'}]} ,
    { code: 'KA27', value: 'Udupi Chikmagalur', ministers: [{name: 'Shobha Karandlaje', id: 'm-ka27'}]} ,
    { code: 'KA28', value: 'Uttara Kannada', ministers: [{name: 'Anant Kumar Hegde', id: 'm-ka28'}]} ],

  'KL':[
    { code: 'KL1', value: 'Alappuzha', ministers: [{name: 'K. C. Venugopal', id: 'm-kl1'}]} ,
    { code: 'KL2', value: 'Alathur', ministers: [{name: 'P. K. Biju', id: 'm-kl2'}]} ,
    { code: 'KL3', value: 'Attingal', ministers: [{name: 'Anirudhan Sampath', id: 'm-kl3'}]} ,
    { code: 'KL4', value: 'Chalakudy', ministers: [{name: 'Innocent', id: 'm-kl4'}]} ,
    { code: 'KL5', value: 'Ernakulam', ministers: [{name: 'K.V. Thomas', id: 'm-kl5'}]} ,
    { code: 'KL6', value: 'Idukki', ministers: [{name: 'Joice George', id: 'm-kl6'}]} ,
    { code: 'KL7', value: 'Kannur', ministers: [{name: 'P.K. Sreemathi Teacher', id: 'm-kl7'}]} ,
    { code: 'KL8', value: 'Kasaragod', ministers: [{name: 'P. Karunakaran', id: 'm-kl8'}]} ,
    { code: 'KL9', value: 'Kollam', ministers: [{name: 'N.K.Premachandran', id: 'm-kl9'}]} ,
    { code: 'KL10', value: 'Kottayam', ministers: [{name: 'Jose K. Mani', id: 'm-kl10'}]} ,
    { code: 'KL11', value: 'Kozhikode', ministers: [{name: 'M. K. Raghavan', id: 'm-kl11'}]} ,
    { code: 'KL13', value: 'Malappuram', ministers: [{name: 'P.K. Kunhalikutty', id: 'm-kl13'}]} ,
    { code: 'KL14', value: 'Mavelikkara', ministers: [{name: 'Suresh Kodikunnil', id: 'm-kl14'}]} ,
    { code: 'KL15', value: 'Palakkad', ministers: [{name: 'M. B. Rajesh', id: 'm-kl15'}]} ,
    { code: 'KL16', value: 'Pathanamthitta', ministers: [{name: 'Anto Antony', id: 'm-kl16'}]} ,
    { code: 'KL17', value: 'Ponnani', ministers: [{name: 'E. T. Mohammed Basheer', id: 'm-kl17'}]} ,
    { code: 'KL18', value: 'Thiruvananthapuram', ministers: [{name: 'Shashi Tharoor', id: 'm-kl18'}]} ,
    { code: 'KL19', value: 'Thrissur', ministers: [{name: 'C.N. Jayadevan', id: 'm-kl19'}]} ,
    { code: 'KL20', value: 'Vadakara', ministers: [{name: 'Ramachandran Mullappally', id: 'm-kl20'}]} ,
    { code: 'KL21', value: 'Wayanad', ministers: [{name: 'M. I. Shanavas', id: 'm-kl21'}]} ],


  'LD':[{ code: 'LD1', value: 'Lakshadweep', ministers: [{name: 'P.P. Mohammed Faizal', id: 'm-ld1'}]} ],

  'MP':[
    { code: 'MP1', value: 'Balaghat', ministers: [{name: 'Bodhsingh Bhagat', id: 'm-mp1'}]} ,
    { code: 'MP2', value: 'Betul', ministers: [{name: 'Jyoti Dhurve', id: 'm-mp2'}]} ,
    { code: 'MP3', value: 'Bhind', ministers: [{name: 'Bhagirath Prasad', id: 'm-mp3'}]} ,
    { code: 'MP4', value: 'Bhopal', ministers: [{name: 'Alok Sanjar', id: 'm-mp4'}]} ,
    { code: 'MP5', value: 'Chhindwara', ministers: [{name: 'Kamal Nath', id: 'm-mp5'}]} ,
    { code: 'MP6', value: 'Damoh', ministers: [{name: 'Prahlad Singh Patel', id: 'm-mp6'}]} ,
    { code: 'MP7', value: 'Dewas', ministers: [{name: 'Manohar Untwal', id: 'm-mp7'}]} ,
    { code: 'MP8', value: 'Dhar', ministers: [{name: 'Savitri Thakur', id: 'm-mp8'}]} ,
    { code: 'MP9', value: 'Guna', ministers: [{name: 'Jyotiraditya Madhavrao Scindia', id: 'm-mp9'}]} ,
    { code: 'MP10', value: 'Gwalior', ministers: [{name: 'Narendra Singh Tomar', id: 'm-mp10'}]} ,
    { code: 'MP11', value: 'Hoshangabad', ministers: [{name: 'Uday Pratap Singh', id: 'm-mp11'}]} ,
    { code: 'MP12', value: 'Indore', ministers: [{name: 'Sumitra Mahajan', id: 'm-mp12'}]} ,
    { code: 'MP13', value: 'Jabalpur', ministers: [{name: 'Rakesh Singh', id: 'm-mp13'}]} ,
    { code: 'MP14', value: 'Khajuraho', ministers: [{name: 'Nagendra Singh', id: 'm-mp14'}]} ,
    { code: 'MP15', value: 'Khandwa', ministers: [{name: 'Nandkumar Singh Chouhan (Nandu Bhaiya)', id: 'm-mp15'}]} ,
    { code: 'MP16', value: 'Khargone', ministers: [{name: 'Subhash Patel', id: 'm-mp16'}]} ,
    { code: 'MP17', value: 'Mandla', ministers: [{name: 'Faggan Singh Kulaste', id: 'm-mp17'}]} ,
    { code: 'MP18', value: 'Mandsour', ministers: [{name: 'Sudhir Gupta', id: 'm-mp18'}]} ,
    { code: 'MP19', value: 'Morena', ministers: [{name: 'Anoop Mishra', id: 'm-mp19'}]} ,
    { code: 'MP20', value: 'Rajgarh', ministers: [{name: 'Rodmal Nagar', id: 'm-mp20'}]} ,
    { code: 'MP22', value: 'Ratlam', ministers: [{name: 'Kantilal Bhuria', id: 'm-mp22'}]} ,
    { code: 'MP23', value: 'Rewa', ministers: [{name: 'Janardan Mishra', id: 'm-mp23'}]} ,
    { code: 'MP24', value: 'Sagar', ministers: [{name: 'Laxmi Narayan Yadav', id: 'm-mp24'}]} ,
    { code: 'MP25', value: 'Satna', ministers: [{name: 'Ganesh Singh', id: 'm-mp25'}]} ,
    { code: 'MP27', value: 'Shahdol', ministers: [{name: 'Gyan Singh', id: 'm-mp27'}]} ,
    { code: 'MP28', value: 'Sidhi', ministers: [{name: 'Riti Pathak', id: 'm-mp28'}]} ,
    { code: 'MP29', value: 'Tikamgarh', ministers: [{name: 'Virendra Kumar', id: 'm-mp29'}]} ,
    { code: 'MP30', value: 'Ujjain', ministers: [{name: 'Chintamani Malviya', id: 'm-mp30'}]} ,
    { code: 'MP31', value: 'Vidisha', ministers: [{name: 'Sushma Swaraj', id: 'm-mp31'}]} ],

  'MH':[
    { code: 'MH1', value: 'Ahmednagar', ministers: [{name: 'Dilip Kumar Mansukhlal Gandhi', id: 'm-mh1'}]} ,
    { code: 'MH2', value: 'Akola', ministers: [{name: 'Sanjay Shamrao Dhotre', id: 'm-mh2'}]} ,
    { code: 'MH3', value: 'Amravati', ministers: [{name: 'Anandrao Adsul', id: 'm-mh3'}]} ,
    { code: 'MH4', value: 'Aurangabad', ministers: [{name: 'Chandrakant Bhaurao Khaire', id: 'm-mh4'}]} ,
    { code: 'MH6', value: 'Beed', ministers: [{name: 'Pritam Gopinath Munde', id: 'm-mh6'}]} ,
    { code: 'MH7', value: 'Bhandara-Gondiya', ministers: [{name: 'Madhukrao Yashwantrao Kukade', id: 'm-mh7'}]} ,
    { code: 'MH9', value: 'Bhiwandi', ministers: [{name: 'Kapil Moreshwar Patil', id: 'm-mh9'}]} ,
    { code: 'MH10', value: 'Buldhana', ministers: [{name: 'Jadhav Prataprao Ganpatrao', id: 'm-mh10'}]} ,
    { code: 'MH11', value: 'Chandrapur', ministers: [{name: 'Hansraj Gangaram Ahir', id: 'm-mh11'}]} ,
    { code: 'MH12', value: 'Dhule', ministers: [{name: 'Subhash Ramrao Bhamre', id: 'm-mh12'}]} ,
    { code: 'MH13', value: 'Dindori', ministers: [{name: 'Harishchandra Deoram Chavan', id: 'm-mh13'}]} ,
    { code: 'MH14', value: 'Gadchiroli-Chimur', ministers: [{name: 'Ashok Mahadeorao Nete', id: 'm-mh14'}]} ,
    { code: 'MH15', value: 'Hatkanangle', ministers: [{name: 'Raju Shetti', id: 'm-mh15'}]} ,
    { code: 'MH16', value: 'Hingoli', ministers: [{name: 'Rajeev Shankarrao Satav', id: 'm-mh16'}]} ,
    { code: 'MH17', value: 'Jalgaon', ministers: [{name: 'A.T. Nana Patil', id: 'm-mh17'}]} ,
    { code: 'MH18', value: 'Jalna', ministers: [{name: 'Raosaheb Patil Danve', id: 'm-mh18'}]} ,
    { code: 'MH19', value: 'Kalyan', ministers: [{name: 'Shrikant Eknath Shinde', id: 'm-mh19'}]} ,
    { code: 'MH20', value: 'Kolhapur', ministers: [{name: 'Dhananjay Bhimrao Mahadik', id: 'm-mh20'}]} ,
    { code: 'MH21', value: 'Latur', ministers: [{name: 'Sunil Baliram Gaikwad', id: 'm-mh21'}]} ,
    { code: 'MH22', value: 'Madha', ministers: [{name: 'Vijaysinh Shankarrao Mohite Patil', id: 'm-mh22'}]} ,
    { code: 'MH23', value: 'Maval', ministers: [{name: 'Shrirang Appa Barne', id: 'm-mh23'}]} ,
    { code: 'MH24', value: 'Mumbai-North', ministers: [{name: 'Gopal Chinayya Shetty', id: 'm-mh24'}]} ,
    { code: 'MH25', value: 'Mumbai-North-Central', ministers: [{name: 'Poonam Mahajan Alias Poonam Vajendla Rao', id: 'm-mh25'}]} ,
    { code: 'MH26', value: 'Mumbai-North-East', ministers: [{name: 'Kirit Somaiya', id: 'm-mh26'}]} ,
    { code: 'MH27', value: 'Mumbai-North-West', ministers: [{name: 'Gajanan Chandrakant Kirtikar', id: 'm-mh27'}]} ,
    { code: 'MH28', value: 'Mumbai-South', ministers: [{name: 'Arvind Sawant', id: 'm-mh28'}]} ,
    { code: 'MH29', value: 'Mumbai-South-Central', ministers: [{name: 'Rahul Ramesh Shewale', id: 'm-mh29'}]} ,
    { code: 'MH30', value: 'Nagpur', ministers: [{name: 'Nitin Jairam Gadkari', id: 'm-mh30'}]} ,
    { code: 'MH31', value: 'Nanded', ministers: [{name: 'Ashok Shankarrao Chavan', id: 'm-mh31'}]} ,
    { code: 'MH32', value: 'Nandurbar', ministers: [{name: 'Heena Vaijaykumar Gavit', id: 'm-mh32'}]} ,
    { code: 'MH33', value: 'Nashik', ministers: [{name: 'Godse Hemant Tukaram', id: 'm-mh33'}]} ,
    { code: 'MH34', value: 'Osmanabad', ministers: [{name: 'Ravindra Vishwanath Gaikwad', id: 'm-mh34'}]} ,
    { code: 'MH36', value: 'Palghar', ministers: [{name: 'Rajendra Dhedya Gavit', id: 'm-mh36'}]} ,
    { code: 'MH37', value: 'Parbhani', ministers: [{name: 'Sanjay (Bandu) Haribhau Jadhav', id: 'm-mh37'}]} ,
    { code: 'MH38', value: 'Pune', ministers: [{name: 'Anil Shirole', id: 'm-mh38'}]} ,
    { code: 'MH39', value: 'Raigad', ministers: [{name: 'Anant Gangaram Geete', id: 'm-mh39'}]} ,
    { code: 'MH40', value: 'Ramtek', ministers: [{name: 'Krupal Balaji Tumane', id: 'm-mh40'}]} ,
    { code: 'MH41', value: 'Ratnagiri-Sindhudurg', ministers: [{name: 'Vinayak Bhaurao Raut', id: 'm-mh41'}]} ,
    { code: 'MH42', value: 'Raver', ministers: [{name: 'Raksha Nikhil Khadase', id: 'm-mh42'}]} ,
    { code: 'MH43', value: 'Sangli', ministers: [{name: 'Sanjaykaka Patil', id: 'm-mh43'}]} ,
    { code: 'MH44', value: 'Satara', ministers: [{name: 'Shrimant Chh. Udyanraje Pratapsinhmaharaj Bhonsle', id: 'm-mh44'}]} ,
    { code: 'MH45', value: 'Shirdi', ministers: [{name: 'Sadashiv Kisan Lokhande', id: 'm-mh45'}]} ,
    { code: 'MH46', value: 'Shirur', ministers: [{name: 'Shivaji Adhalrao Patil', id: 'm-mh46'}]} ,
    { code: 'MH47', value: 'Solapur', ministers: [{name: 'Sharad Bansode', id: 'm-mh47'}]} ,
    { code: 'MH48', value: 'Thane', ministers: [{name: 'Rajan Baburao Vichare', id: 'm-mh48'}]} ,
    { code: 'MH49', value: 'Wardha', ministers: [{name: 'Ramdas Chandrabhanji Tadas', id: 'm-mh49'}]} ,
    { code: 'MH50', value: 'Yavatmal-Washim', ministers: [{name: 'Bhavana Pundlikrao Gawali Patil', id: 'm-mh50'}]} ],

  'MN':[
    { code: 'MN1', value: 'Outer Manipur', ministers: [{name: 'Thangso Baite', id: 'm-mn1'}]} ,
    { code: 'MN2', value: 'Inner Manipur', ministers: [{name: 'Thokchom Meinya', id: 'm-mn2'}]} ],


  'ML':[{ code: 'ML1', value: 'Tura', ministers: [{name: 'Conrad Kongkal Sangma', id: 'm-ml1'}]} ,
    { code: 'ML3', value: 'Shillong', ministers: [{name: 'Vincent H Pala', id: 'm-ml3'}]} ],


  'MZ':[{ code: 'MZ1', value: 'Mizoram', ministers: [{name: 'C. L. Ruala', id: 'm-mz1'}]} ],


  'NL':[{ code: 'NL2', value: 'Nagaland', ministers: [{name: 'Tokheho', id: 'm-nl2'}]} ],

  'OR':[
    { code: 'OR1', value: 'Aska', ministers: [{name: 'Ladu Kishore Swain', id: 'm-or1'}]} ,
    { code: 'OR2', value: 'Balasore', ministers: [{name: 'Rabindra Kumar Jena', id: 'm-or2'}]} ,
    { code: 'OR3', value: 'Bargarh', ministers: [{name: 'Prabhas Kumar Singh', id: 'm-or3'}]} ,
    { code: 'OR4', value: 'Berhampur', ministers: [{name: 'Sidhant Mohapatra', id: 'm-or4'}]} ,
    { code: 'OR5', value: 'Bhadrak', ministers: [{name: 'Arjun Charan Sethi', id: 'm-or5'}]} ,
    { code: 'OR6', value: 'Bhubaneswar', ministers: [{name: 'Prasanna Kumar Patasani', id: 'm-or6'}]} ,
    { code: 'OR7', value: 'Bolangir', ministers: [{name: 'Kalikesh Narayan Singh Deo', id: 'm-or7'}]} ,
    { code: 'OR8', value: 'Cuttack', ministers: [{name: 'Bhartruhari Mahtab', id: 'm-or8'}]} ,
    { code: 'OR9', value: 'Dhenkanal', ministers: [{name: 'Tathagata Satpathy', id: 'm-or9'}]} ,
    { code: 'OR10', value: 'Jagatsinghpur', ministers: [{name: 'Kulamani Samal', id: 'm-or10'}]} ,
    { code: 'OR11', value: 'Jajpur', ministers: [{name: 'Rita Tarai', id: 'm-or11'}]} ,
    { code: 'OR12', value: 'Kalahandi', ministers: [{name: 'Arka Keshari Deo', id: 'm-or12'}]} ,
    { code: 'OR14', value: 'Kandhamal', ministers: [{name: 'Pratyusha Rajeshwari Singh', id: 'm-or14'}]} ,
    { code: 'OR15', value: 'Kendrapara', ministers: [{name: 'Baijayant Jay Panda', id: 'm-or15'}]} ,
    { code: 'OR16', value: 'Keonjhar', ministers: [{name: 'Sakuntala Laguri', id: 'm-or16'}]} ,
    { code: 'OR17', value: 'Koraput', ministers: [{name: 'Jhina Hikaka', id: 'm-or17'}]} ,
    { code: 'OR18', value: 'Mayurbhanj', ministers: [{name: 'Rama Chandra Hansdah', id: 'm-or18'}]} ,
    { code: 'OR19', value: 'Nabarangpur', ministers: [{name: 'Balabhadra Majhi', id: 'm-or19'}]} ,
    { code: 'OR20', value: 'Puri', ministers: [{name: 'Pinaki Misra', id: 'm-or20'}]} ,
    { code: 'OR21', value: 'Sambalpur', ministers: [{name: 'Nagendra Kumar Pradhan', id: 'm-or21'}]} ,
    { code: 'OR22', value: 'Sundargarh', ministers: [{name: 'Jual @ Juel Oram', id: 'm-or22'}]} ],


  'PY':[{ code: 'PY1', value: 'Puducherry', ministers: [{name: 'R. Radhakrishnan', id: 'm-py1'}]} ],


  'PB':[
    { code: 'PB2', value: 'Amritsar', ministers: [{name: 'Gurjeet Singh Aujla', id: 'm-pb2'}]} ,
    { code: 'PB3', value: 'Anandpur Sahib', ministers: [{name: 'Prem Singh Chandumajra', id: 'm-pb3'}]} ,
    { code: 'PB4', value: 'Bathinda', ministers: [{name: 'Harsimrat Kaur Badal', id: 'm-pb4'}]} ,
    { code: 'PB5', value: 'Faridkot', ministers: [{name: 'Sadhu Singh', id: 'm-pb5'}]} ,
    { code: 'PB6', value: 'Fatehgarh Sahib', ministers: [{name: 'Harinder Singh Khalsa', id: 'm-pb6'}]} ,
    { code: 'PB7', value: 'Ferozpur', ministers: [{name: 'Sher Singh Ghubaya', id: 'm-pb7'}]} ,
    { code: 'PB8', value: 'Gurdaspur', ministers: [{name: 'Sunil Kumar Jakhar', id: 'm-pb8'}]} ,
    { code: 'PB10', value: 'Hoshiarpur', ministers: [{name: 'Vijay Sampla', id: 'm-pb10'}]} ,
    { code: 'PB11', value: 'Jalandhar', ministers: [{name: 'Santokh Singh Chaudhary', id: 'm-pb11'}]} ,
    { code: 'PB12', value: 'Khadoor Sahib', ministers: [{name: 'Ranjit Singh Brahmpura', id: 'm-pb12'}]} ,
    { code: 'PB13', value: 'Ludhiana', ministers: [{name: 'Ravneet Singh', id: 'm-pb13'}]} ,
    { code: 'PB14', value: 'Patiala', ministers: [{name: 'Dharam Vira Gandhi', id: 'm-pb14'}]} ,
    { code: 'PB15', value: 'Sangrur', ministers: [{name: 'Bhagwant Mann', id: 'm-pb15'}]} ],

  'RJ':[
    { code: 'RJ1', value: 'Ajmer', ministers: [{name: 'Raghu Sharma', id: 'm-rj1'}]} ,
    { code: 'RJ4', value: 'Alwar', ministers: [{name: 'Karan Singh Yadav', id: 'm-rj4'}]} ,
    { code: 'RJ5', value: 'Banswara', ministers: [{name: 'Manshankar Ninama', id: 'm-rj5'}]} ,
    { code: 'RJ6', value: 'Barmer', ministers: [{name: 'Sona Ram', id: 'm-rj6'}]} ,
    { code: 'RJ7', value: 'Bharatpur', ministers: [{name: 'Bahadur Singh Koli', id: 'm-rj7'}]} ,
    { code: 'RJ8', value: 'Bhilwara', ministers: [{name: 'Subhash Baheria', id: 'm-rj8'}]} ,
    { code: 'RJ9', value: 'Bikaner', ministers: [{name: 'Arjun Ram Meghwal', id: 'm-rj9'}]} ,
    { code: 'RJ10', value: 'Chittorgarh', ministers: [{name: 'Chandra Prakash Joshi', id: 'm-rj10'}]} ,
    { code: 'RJ11', value: 'Churu', ministers: [{name: 'Rahul Kaswan', id: 'm-rj11'}]} ,
    { code: 'RJ12', value: 'Dausa', ministers: [{name: 'Harish Chandra Meena', id: 'm-rj12'}]} ,
    { code: 'RJ13', value: 'Ganganagar', ministers: [{name: 'Nihalchand', id: 'm-rj13'}]} ,
    { code: 'RJ14', value: 'Jaipur', ministers: [{name: 'Ramcharan Bohara', id: 'm-rj14'}]} ,
    { code: 'RJ15', value: 'Jaipur Rural', ministers: [{name: 'Rajyavardhan Singh Rathore', id: 'm-rj15'}]} ,
    { code: 'RJ16', value: 'Jalore', ministers: [{name: 'Devji Patel', id: 'm-rj16'}]} ,
    { code: 'RJ17', value: 'Jhalawar-Baran', ministers: [{name: 'Dushyant Singh', id: 'm-rj17'}]} ,
    { code: 'RJ18', value: 'Jhunjhunu', ministers: [{name: 'Santosh Ahlawat', id: 'm-rj18'}]} ,
    { code: 'RJ19', value: 'Jodhpur', ministers: [{name: 'Gajendrasingh Shekhawat', id: 'm-rj19'}]} ,
    { code: 'RJ20', value: 'Karauli-Dholpur', ministers: [{name: 'Manoj Rajoria', id: 'm-rj20'}]} ,
    { code: 'RJ21', value: 'Kota', ministers: [{name: 'Om Birla', id: 'm-rj21'}]} ,
    { code: 'RJ22', value: 'Nagaur', ministers: [{name: 'C.R. Choudhary', id: 'm-rj22'}]} ,
    { code: 'RJ23', value: 'Pali', ministers: [{name: 'P.P. Chaudhary', id: 'm-rj23'}]} ,
    { code: 'RJ24', value: 'Rajsamand', ministers: [{name: 'Hariom Singh Rathore', id: 'm-rj24'}]} ,
    { code: 'RJ25', value: 'Sikar', ministers: [{name: 'Sumedhanand Saraswati', id: 'm-rj25'}]} ,
    { code: 'RJ26', value: 'Tonk-Sawai Madhopur', ministers: [{name: 'Sukhbir Singh Jaunapuria', id: 'm-rj26'}]},
{ code: 'RJ27', value: 'Udaipur', ministers: [{name: 'Arjunlal Meena', id: 'm-rj27'}]}],


'SK':[{ code: 'SK1', value: 'Sikkim', ministers: [{name: 'Prem Das Rai', id: 'm-sk1'}]} ],

  'TN':[
  { code: 'TN1', value: 'Arakkonam', ministers: [{name: 'G. Hari', id: 'm-tn1'}]} ,
  { code: 'TN2', value: 'Arani', ministers: [{name: 'V. Elumalai', id: 'm-tn2'}]} ,
  { code: 'TN3', value: 'Chennai Central', ministers: [{name: 'S.R. Vijayakumar', id: 'm-tn3'}]} ,
  { code: 'TN4', value: 'Chennai North', ministers: [{name: 'T.G. Venkatesh Babu', id: 'm-tn4'}]} ,
  { code: 'TN5', value: 'Chennai South', ministers: [{name: 'J. Jayavardhan', id: 'm-tn5'}]} ,
  { code: 'TN6', value: 'Chidambaram', ministers: [{name: 'M. Chandrakasi', id: 'm-tn6'}]} ,
  { code: 'TN7', value: 'Coimbatore', ministers: [{name: 'P. Nagarajan', id: 'm-tn7'}]} ,
  { code: 'TN8', value: 'Cuddalore', ministers: [{name: 'A. Arunmozhithevan', id: 'm-tn8'}]} ,
  { code: 'TN9', value: 'Dharmapuri', ministers: [{name: 'Anbumani Ramadoss', id: 'm-tn9'}]} ,
  { code: 'TN10', value: 'Dindigul', ministers: [{name: 'M. Udhaya Kumar', id: 'm-tn10'}]} ,
  { code: 'TN11', value: 'Erode', ministers: [{name: 'S. Selvakumara Chinnayan', id: 'm-tn11'}]} ,
  { code: 'TN12', value: 'Kallakurichi', ministers: [{name: 'K. Kamaraj', id: 'm-tn12'}]} ,
  { code: 'TN13', value: 'Kancheepuram', ministers: [{name: 'K. Maragatham', id: 'm-tn13'}]} ,
  { code: 'TN14', value: 'Kanniyakumari', ministers: [{name: 'P. Radhakrishnan', id: 'm-tn14'}]} ,
  { code: 'TN15', value: 'Karur', ministers: [{name: 'Munisamy Thambidurai', id: 'm-tn15'}]} ,
  { code: 'TN16', value: 'Krisnagiri', ministers: [{name: 'K. Ashok Kumar', id: 'm-tn16'}]} ,
  { code: 'TN17', value: 'Madurai', ministers: [{name: 'R. Gopalakrishnan', id: 'm-tn17'}]} ,
  { code: 'TN18', value: 'Mayiladuthurai', ministers: [{name: 'R.K. Bharathi Mohan', id: 'm-tn18'}]} ,
  { code: 'TN19', value: 'Nagapattinam', ministers: [{name: 'K. Gopal', id: 'm-tn19'}]} ,
  { code: 'TN20', value: 'Namakkal', ministers: [{name: 'P.R. Sundaram', id: 'm-tn20'}]} ,
  { code: 'TN21', value: 'Nilgiris', ministers: [{name: 'C. Gopalakrishnan', id: 'm-tn21'}]} ,
  { code: 'TN22', value: 'Perambalur', ministers: [{name: 'R.P. Marutharajaa', id: 'm-tn22'}]} ,
  { code: 'TN23', value: 'Pollachi', ministers: [{name: 'C. Mahendran', id: 'm-tn23'}]} ,
  { code: 'TN24', value: 'Ramanthapuram', ministers: [{name: 'A. Anwhar Raajhaa', id: 'm-tn24'}]} ,
  { code: 'TN25', value: 'Salem', ministers: [{name: 'V. Pannerselvam', id: 'm-tn25'}]} ,
  { code: 'TN26', value: 'Sivaganga', ministers: [{name: 'P.R. Senthilnathan', id: 'm-tn26'}]} ,
  { code: 'TN27', value: 'Sriperumbudur', ministers: [{name: 'K.N. Ramachandran', id: 'm-tn27'}]} ,
  { code: 'TN28', value: 'Tenkasi', ministers: [{name: 'M. Vasanthi', id: 'm-tn28'}]} ,
  { code: 'TN29', value: 'Thanjavur', ministers: [{name: 'K. Parasuraman', id: 'm-tn29'}]} ,
  { code: 'TN30', value: 'Theni', ministers: [{name: 'R. Parthipan', id: 'm-tn30'}]} ,
  { code: 'TN31', value: 'Thoothukkudi', ministers: [{name: 'J. Jeyasingh Thiyagaraj Natterjee', id: 'm-tn31'}]} ,
  { code: 'TN32', value: 'Tiruchirappalli', ministers: [{name: 'P. Kumar', id: 'm-tn32'}]} ,
  { code: 'TN33', value: 'Tirunelveli', ministers: [{name: 'K.R.P.  Prabakaran', id: 'm-tn33'}]} ,
  { code: 'TN34', value: 'Tiruppur', ministers: [{name: 'V. Sathyabama', id: 'm-tn34'}]} ,
  { code: 'TN35', value: 'Tiruvallur', ministers: [{name: 'P. Venugopal', id: 'm-tn35'}]} ,
  { code: 'TN36', value: 'Tiruvannamalai', ministers: [{name: 'R. Vanaroja', id: 'm-tn36'}]} ,
  { code: 'TN37', value: 'Vellore', ministers: [{name: 'B. Senguttuvan', id: 'm-tn37'}]} ,
  { code: 'TN38', value: 'Viluppuram', ministers: [{name: 'S. Rajendran', id: 'm-tn38'}]} ,
  { code: 'TN39', value: 'Virudhunagar', ministers: [{name: 'T. Radhakrishnan', id: 'm-tn39'}]} ],

  'TL':[
  { code: 'TL1', value: 'Adilabad', ministers: [{name: 'Godam Nagesh', id: 'm-tl1'}]} ,
  { code: 'TL2', value: 'Bhongir', ministers: [{name: 'Boora Narsaiah Goud', id: 'm-tl2'}]} ,
  { code: 'TL3', value: 'Chelvella', ministers: [{name: 'Konda Vishweshwar Reddy', id: 'm-tl3'}]} ,
  { code: 'TL4', value: 'Hyderabad', ministers: [{name: 'Asaduddin Owaisi', id: 'm-tl4'}]} ,
  { code: 'TL5', value: 'Karimnagar', ministers: [{name: 'Vinod Kumar Boinapally', id: 'm-tl5'}]} ,
  { code: 'TL6', value: 'Khammam', ministers: [{name: 'Ponguleti Srinivasa Reddy', id: 'm-tl6'}]} ,
  { code: 'TL7', value: 'Mahabubabad', ministers: [{name: 'Azmeera Seetaram Naik', id: 'm-tl7'}]} ,
  { code: 'TL8', value: 'Mahabubnagar', ministers: [{name: 'A.P. Jithender Reddy', id: 'm-tl8'}]} ,
  { code: 'TL9', value: 'Malkajgiri', ministers: [{name: 'Malla Reddy', id: 'm-tl9'}]} ,
  { code: 'TL10', value: 'Medak', ministers: [{name: 'Kotha Prabhakar Reddy', id: 'm-tl10'}]} ,
  { code: 'TL11', value: 'Nagarkurnool', ministers: [{name: 'Yellaiah Nandi', id: 'm-tl11'}]} ,
  { code: 'TL12', value: 'Nalgonda', ministers: [{name: 'Sukender Reddy Gutha', id: 'm-tl12'}]} ,
  { code: 'TL13', value: 'Nizamabad', ministers: [{name: 'Kalvakuntla Kavitha', id: 'm-tl13'}]} ,
  { code: 'TL14', value: 'Peddapalle', ministers: [{name: 'Balka Suman', id: 'm-tl14'}]} ,
  { code: 'TL15', value: 'Secunderabad', ministers: [{name: 'Bandaru Dattatreya', id: 'm-tl15'}]} ,
  { code: 'TL17', value: 'Warangal', ministers: [{name: 'Dayakar Pasunoori', id: 'm-tl17'}]} ,
  { code: 'TL18', value: 'Zahirabad', ministers: [{name: 'Bheemrao B. Patil', id: 'm-tl18'}]} ],

  'TR':[
  { code: 'TR1', value: 'Tripura East', ministers: [{name: 'Jitendra Choudhury', id: 'm-tr1'}]} ,
  { code: 'TR2', value: 'Tripura West', ministers: [{name: 'Sankar Prasad Datta', id: 'm-tr2'}]} ],

  'UP':[
  { code: 'UP1', value: 'Agra', ministers: [{name: 'Ram Shankar Katheria', id: 'm-up1'}]} ,
  { code: 'UP2', value: 'Akbarpur', ministers: [{name: 'Devendra Singh @ Bhole Singh', id: 'm-up2'}]} ,
  { code: 'UP3', value: 'Aligarh', ministers: [{name: 'Satish Kumar', id: 'm-up3'}]} ,
  { code: 'UP4', value: 'Allahabad', ministers: [{name: 'Shyama Charan Gupta', id: 'm-up4'}]} ,
  { code: 'UP5', value: 'Ambedkar Nagar', ministers: [{name: 'Hari Om Pandey', id: 'm-up5'}]} ,
  { code: 'UP6', value: 'Amethi', ministers: [{name: 'Rahul Gandhi', id: 'm-up6'}]} ,
  { code: 'UP7', value: 'Amroha', ministers: [{name: 'Kanwar Singh Tanwar', id: 'm-up7'}]} ,
  { code: 'UP8', value: 'Aonla', ministers: [{name: 'Dharmendra Kumar', id: 'm-up8'}]} ,
  { code: 'UP9', value: 'Azamgarh', ministers: [{name: 'Mulayam Singh Yadav', id: 'm-up9'}]} ,
  { code: 'UP10', value: 'Badaun', ministers: [{name: 'Dharmendra Yadav', id: 'm-up10'}]} ,
  { code: 'UP11', value: 'Baghpat', ministers: [{name: 'Satya Pal Singh', id: 'm-up11'}]} ,
  { code: 'UP12', value: 'Bahraich', ministers: [{name: 'Savitri Bai Foole', id: 'm-up12'}]} ,
  { code: 'UP13', value: 'Ballia', ministers: [{name: 'Bharat Singh', id: 'm-up13'}]} ,
  { code: 'UP14', value: 'Banda', ministers: [{name: 'Bhairon Prasad Mishra', id: 'm-up14'}]} ,
  { code: 'UP15', value: 'Bansgaon', ministers: [{name: 'Kamlesh Paswan', id: 'm-up15'}]} ,
  { code: 'UP16', value: 'Barabanki', ministers: [{name: 'Priyanka Singh Rawat', id: 'm-up16'}]} ,
  { code: 'UP17', value: 'Bareilly', ministers: [{name: 'Santosh Kumar Gangwar', id: 'm-up17'}]} ,
  { code: 'UP18', value: 'Basti', ministers: [{name: 'Harish Chandra Alias Harish Dwivedi', id: 'm-up18'}]} ,
  { code: 'UP19', value: 'Bhadohi', ministers: [{name: 'Virendra Singh', id: 'm-up19'}]} ,
  { code: 'UP20', value: 'Bijnor', ministers: [{name: 'Bharatendra Singh', id: 'm-up20'}]} ,
  { code: 'UP21', value: 'Bulandshahr', ministers: [{name: 'Bhola Singh', id: 'm-up21'}]} ,
  { code: 'UP22', value: 'Chandauli', ministers: [{name: 'Mahendra Nath Pandey', id: 'm-up22'}]} ,
  { code: 'UP23', value: 'Deoria', ministers: [{name: 'Kalraj Mishra', id: 'm-up23'}]} ,
  { code: 'UP24', value: 'Dhaurahra', ministers: [{name: 'Rekha Verma', id: 'm-up24'}]} ,
  { code: 'UP25', value: 'Domariyaganj', ministers: [{name: 'Jagdambika Pal', id: 'm-up25'}]} ,
  { code: 'UP26', value: 'Etah', ministers: [{name: 'Rajveer Singh (Raju Bhaiya)', id: 'm-up26'}]} ,
  { code: 'UP27', value: 'Etawah', ministers: [{name: 'Ashok Kumar Doharey', id: 'm-up27'}]} ,
  { code: 'UP28', value: 'Faizabad', ministers: [{name: 'Lallu Singh', id: 'm-up28'}]} ,
  { code: 'UP29', value: 'Farrukhabad', ministers: [{name: 'Mukesh Rajput', id: 'm-up29'}]} ,
  { code: 'UP30', value: 'Fatehpur', ministers: [{name: 'Niranjan Jyoti', id: 'm-up30'}]} ,
  { code: 'UP31', value: 'Fatehpur Sikri', ministers: [{name: 'Babulal Chaudhary', id: 'm-up31'}]} ,
  { code: 'UP32', value: 'Firozabad', ministers: [{name: 'Akshay Yadav', id: 'm-up32'}]} ,
  { code: 'UP33', value: 'Gautam Buddha Nagar', ministers: [{name: 'Mahesh Sharma', id: 'm-up33'}]} ,
  { code: 'UP34', value: 'Ghaziabad', ministers: [{name: 'Vijay Kumar Singh', id: 'm-up34'}]} ,
  { code: 'UP35', value: 'Ghazipur', ministers: [{name: 'Manoj Sinha', id: 'm-up35'}]} ,
  { code: 'UP36', value: 'Ghosi', ministers: [{name: 'Harinarayan Rajbhar', id: 'm-up36'}]} ,
  { code: 'UP37', value: 'Gonda', ministers: [{name: 'Kirti Vardhan Singh', id: 'm-up37'}]} ,
  { code: 'UP38', value: 'Gorakhpur', ministers: [{name: 'Pravin Kumar Nishad', id: 'm-up38'}]} ,
  { code: 'UP40', value: 'Hamirpur', ministers: [{name: 'Pushpendra Singh Chandel', id: 'm-up40'}]} ,
  { code: 'UP41', value: 'Hardoi', ministers: [{name: 'Anshul Verma', id: 'm-up41'}]} ,
  { code: 'UP42', value: 'Hathras', ministers: [{name: 'Rajesh Kumar Diwaker', id: 'm-up42'}]} ,
  { code: 'UP43', value: 'Jalaun', ministers: [{name: 'Bhanu Pratap Singh Verma', id: 'm-up43'}]} ,
  { code: 'UP44', value: 'Jaunpur', ministers: [{name: 'Krishna Pratap K.P.', id: 'm-up44'}]} ,
  { code: 'UP45', value: 'Jhansi', ministers: [{name: 'Uma Bharati', id: 'm-up45'}]} ,
  { code: 'UP46', value: 'Kairana', ministers: [{name: 'Begum Tabassum Hasan', id: 'm-up46'}]} ,
  { code: 'UP48', value: 'Kaiserganj', ministers: [{name: 'Brij Bhushan Sharan Singh', id: 'm-up48'}]} ,
  { code: 'UP49', value: 'Kannauj', ministers: [{name: 'Dimple Yadav', id: 'm-up49'}]} ,
  { code: 'UP50', value: 'Kanpur', ministers: [{name: 'Murli Manohar Joshi', id: 'm-up50'}]} ,
  { code: 'UP51', value: 'Kaushambi', ministers: [{name: 'Vinod Kumar Sonkar', id: 'm-up51'}]} ,
  { code: 'UP52', value: 'Kheri', ministers: [{name: 'Ajay Misra Teni', id: 'm-up52'}]} ,
  { code: 'UP53', value: 'Khushi Nagar', ministers: [{name: 'Rajesh Pandey Urf Guddu', id: 'm-up53'}]} ,
  { code: 'UP54', value: 'Lalganj', ministers: [{name: 'Neelam Sonkar', id: 'm-up54'}]} ,
  { code: 'UP55', value: 'Lucknow', ministers: [{name: 'Rajnath Singh', id: 'm-up55'}]} ,
  { code: 'UP56', value: 'Machhlishahr', ministers: [{name: 'Ram Charitra Nishad', id: 'm-up56'}]} ,
  { code: 'UP57', value: 'Maharajganj', ministers: [{name: 'Pankaj Chowdhary', id: 'm-up57'}]} ,
  { code: 'UP58', value: 'Mainpuri', ministers: [{name: 'Tej Pratap Singh Yadav', id: 'm-up58'}]} ,
  { code: 'UP59', value: 'Mathura', ministers: [{name: 'Hema Malini', id: 'm-up59'}]} ,
  { code: 'UP60', value: 'Meerut', ministers: [{name: 'Rajendra Agrawal', id: 'm-up60'}]} ,
  { code: 'UP61', value: 'Mirzapur', ministers: [{name: 'Anupriya Singh Patel', id: 'm-up61'}]} ,
  { code: 'UP62', value: 'Misrikh', ministers: [{name: 'Anju Bala', id: 'm-up62'}]} ,
  { code: 'UP63', value: 'Mohanlalganj', ministers: [{name: 'Kaushal Kishore', id: 'm-up63'}]} ,
  { code: 'UP64', value: 'Moradabad', ministers: [{name: 'Kunwer Sarvesh Kumar', id: 'm-up64'}]} ,
  { code: 'UP65', value: 'Muzaffarnagar', ministers: [{name: 'Sanjeev Kumar Balyan', id: 'm-up65'}]} ,
  { code: 'UP66', value: 'Nagina', ministers: [{name: 'Yashwant Singh', id: 'm-up66'}]} ,
  { code: 'UP68', value: 'Phulpur', ministers: [{name: 'Nagendra Pratap Singh Patel', id: 'm-up68'}]} ,
  { code: 'UP69', value: 'Pilibhit', ministers: [{name: 'Maneka Gandhi', id: 'm-up69'}]} ,
  { code: 'UP70', value: 'Pratapgarh', ministers: [{name: 'Haribansh Singh', id: 'm-up70'}]} ,
  { code: 'UP71', value: 'Rae Bareli', ministers: [{name: 'Sonia Gandhi', id: 'm-up71'}]} ,
  { code: 'UP72', value: 'Rampur', ministers: [{name: 'Nepal Singh', id: 'm-up72'}]} ,
  { code: 'UP73', value: 'Robertsganj', ministers: [{name: 'Chhotelal', id: 'm-up73'}]} ,
  { code: 'UP74', value: 'Saharanpur', ministers: [{name: 'Raghav Lakhanpal', id: 'm-up74'}]} ,
  { code: 'UP75', value: 'Salempur', ministers: [{name: 'Ravindra Kushawaha', id: 'm-up75'}]} ,
  { code: 'UP76', value: 'Sambhal', ministers: [{name: 'Satyapal Singh', id: 'm-up76'}]} ,
  { code: 'UP77', value: 'Sant Kabir Nagar', ministers: [{name: 'Sharad Tripathi', id: 'm-up77'}]} ,
  { code: 'UP78', value: 'Shahjahanpur', ministers: [{name: 'Krishna Raj', id: 'm-up78'}]} ,
  { code: 'UP79', value: 'Shrawasti', ministers: [{name: 'Daddan Mishra', id: 'm-up79'}]} ,
  { code: 'UP80', value: 'Sitapur', ministers: [{name: 'Rajesh Verma', id: 'm-up80'}]} ,
  { code: 'UP81', value: 'Sultanpur', ministers: [{name: 'Feroze Varun Gandhi', id: 'm-up81'}]} ,
  { code: 'UP82', value: 'Unnao', ministers: [{name: 'Swami Sachchidanand Hari Sakshi', id: 'm-up82'}]} ,
  { code: 'UP83', value: 'Varanasi', ministers: [{name: 'Narendra Modi', id: 'm-up83'}]} ],

  'UK':[
  { code: 'UK1', value: 'Almora', ministers: [{name: 'Ajay Tamta', id: 'm-uk1'}]} ,
  { code: 'UK2', value: 'Nainital-Udhamsingh Nagar', ministers: [{name: 'Bhagat Singh Koshyari', id: 'm-uk2'}]} ,
  { code: 'UK3', value: 'Garhwal', ministers: [{name: 'Bhuwan Chandra Khanduri', id: 'm-uk3'}]} ,
  { code: 'UK4', value: 'Tehri Garhwal', ministers: [{name: 'Mala Rajya Laxmi Shah', id: 'm-uk4'}]} ,
  { code: 'UK5', value: 'Hardwar', ministers: [{name: 'Ramesh Pokhriyal Nishank', id: 'm-uk5'}]} ],

  'WB':[
  { code: 'WB1', value: 'Alipurduars', ministers: [{name: 'Dasrath Tirkey', id: 'm-wb1'}]} ,
  { code: 'WB2', value: 'Arambagh', ministers: [{name: 'Aparupa Poddar (Afrin Ali)', id: 'm-wb2'}]} ,
  { code: 'WB3', value: 'Asansol', ministers: [{name: 'Babul Supriya Baral (Babul Supriyo)', id: 'm-wb3'}]} ,
  { code: 'WB4', value: 'Baharampur', ministers: [{name: 'Adhir Ranjan Chowdhury', id: 'm-wb4'}]} ,
  { code: 'WB5', value: 'Balurghat', ministers: [{name: 'Arpita Ghosh', id: 'm-wb5'}]} ,
  { code: 'WB6', value: 'Bankura', ministers: [{name: 'Sreemati Dev Varma (Moon Moon Sen)', id: 'm-wb6'}]} ,
  { code: 'WB7', value: 'Barasat', ministers: [{name: 'Kakoli Ghosh Dastidar', id: 'm-wb7'}]} ,
  { code: 'WB8', value: 'Bardhaman Purba', ministers: [{name: 'Sunil Kumar Mondal', id: 'm-wb8'}]} ,
  { code: 'WB9', value: 'Bardhaman-Durgapur', ministers: [{name: 'Mamtaz Sanghamita', id: 'm-wb9'}]} ,
  { code: 'WB10', value: 'Barrackpur', ministers: [{name: 'Dinesh Trivedi', id: 'm-wb10'}]} ,
  { code: 'WB11', value: 'Basirhat', ministers: [{name: 'Idris Ali', id: 'm-wb11'}]} ,
  { code: 'WB12', value: 'Birbhum', ministers: [{name: 'Satabdi Roy', id: 'm-wb12'}]} ,
  { code: 'WB13', value: 'Bishnupur', ministers: [{name: 'Saumitra Khan', id: 'm-wb13'}]} ,
  { code: 'WB14', value: 'Bolpur', ministers: [{name: 'Anupam Hazra', id: 'm-wb14'}]} ,
  { code: 'WB16', value: 'Bongaon', ministers: [{name: 'Mamata Thakur', id: 'm-wb16'}]} ,
  { code: 'WB17', value: 'Cooch Behar', ministers: [{name: 'Partha Pratim Ray', id: 'm-wb17'}]} ,
  { code: 'WB19', value: 'Darjeeling', ministers: [{name: 'S.S. Ahluwalia', id: 'm-wb19'}]} ,
  { code: 'WB20', value: 'Diamond Harbour', ministers: [{name: 'Abhishek Banerjee', id: 'm-wb20'}]} ,
  { code: 'WB21', value: 'Dum Dum', ministers: [{name: 'Saugata Roy', id: 'm-wb21'}]} ,
  { code: 'WB22', value: 'Ghatal', ministers: [{name: 'Adhikari Deepak (Dev)', id: 'm-wb22'}]} ,
  { code: 'WB23', value: 'Hooghly', ministers: [{name: 'Ratna De', id: 'm-wb23'}]} ,
  { code: 'WB24', value: 'Howrah', ministers: [{name: 'Prasun Banerjee', id: 'm-wb24'}]} ,
  { code: 'WB25', value: 'Jadavpur', ministers: [{name: 'Sugata Bose', id: 'm-wb25'}]} ,
  { code: 'WB26', value: 'Jalpaiguri', ministers: [{name: 'Bijoy Chandra Barman', id: 'm-wb26'}]} ,
  { code: 'WB27', value: 'Jangipur', ministers: [{name: 'Abhijit Mukherjee', id: 'm-wb27'}]} ,
  { code: 'WB28', value: 'Jaynagar', ministers: [{name: 'Pratima Mondal', id: 'm-wb28'}]} ,
  { code: 'WB29', value: 'Jhargram', ministers: [{name: 'Uma Saren', id: 'm-wb29'}]} ,
  { code: 'WB30', value: 'Kanthi', ministers: [{name: 'Sisir Kumar Adhikari', id: 'm-wb30'}]} ,
  { code: 'WB31', value: 'Kolkata Dakshin', ministers: [{name: 'Subrata Bakshi', id: 'm-wb31'}]} ,
  { code: 'WB32', value: 'Kolkata Uttar', ministers: [{name: 'Sudip Bandyopadhyay', id: 'm-wb32'}]} ,
  { code: 'WB33', value: 'Krishnanagar', ministers: [{name: 'Tapas Paul', id: 'm-wb33'}]} ,
  { code: 'WB34', value: 'Maldaha Dakshin', ministers: [{name: 'Abu Hasem Khan Choudhury', id: 'm-wb34'}]} ,
  { code: 'WB35', value: 'Maldaha Uttar', ministers: [{name: 'Mausam Noor', id: 'm-wb35'}]} ,
  { code: 'WB36', value: 'Mathurapur', ministers: [{name: 'Choudhury Mohan Jatua', id: 'm-wb36'}]} ,
  { code: 'WB37', value: 'Medinipur', ministers: [{name: 'Sandhya Roy', id: 'm-wb37'}]} ,
  { code: 'WB38', value: 'Murshidabad', ministers: [{name: 'Badaruddoza Khan', id: 'm-wb38'}]} ,
  { code: 'WB39', value: 'Purulia', ministers: [{name: 'Mriganka Mahato', id: 'm-wb39'}]} ,
  { code: 'WB40', value: 'Raiganj', ministers: [{name: 'Md. Salim', id: 'm-wb40'}]} ,
  { code: 'WB41', value: 'Ranaghat', ministers: [{name: 'Tapas Mandal', id: 'm-wb41'}]} ,
  { code: 'WB42', value: 'Serampore', ministers: [{name: 'Kalyan Banerjee', id: 'm-wb42'}]} ,
  { code: 'WB43', value: 'Tamluk', ministers: [{name: 'Dibyendu Adhikari', id: 'm-wb43'}]} ,
  { code: 'WB45', value: 'Uluberia', ministers: [{name: 'Sajda Ahmed', id: 'm-wb45'}]} ]};
